#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspec-fire
Version  : 1.3.0
Release  : 4
URL      : https://rubygems.org/downloads/rspec-fire-1.3.0.gem
Source0  : https://rubygems.org/downloads/rspec-fire-1.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
rspec-fire
==========
Checks that stubbed methods on your test double exist, but still allow you to run in isolation
when you choose. A failure will be triggered if an invalid method is being stubbed.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspec-fire-1.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-rspec-fire.gemspec

%build
gem build rubygem-rspec-fire.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
rspec-fire-1.3.0.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rspec-fire-1.3.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/Configuration/cdesc-Configuration.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/Configuration/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/Configuration/verify_constant_names%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/Configuration/verify_constant_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/AsReplacedConstant/cdesc-AsReplacedConstant.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/AsReplacedConstant/with_doubled_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/StringRepresentations/cdesc-StringRepresentations.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/StringRepresentations/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/StringRepresentations/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/as_replaced_constant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/as_stubbed_const-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/cdesc-FireClassDouble.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireClassDouble/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/cdesc-FireDoublable.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/ensure_implemented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/implemented_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/should_not_receive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/should_receive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/stub%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/stub-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/unimplemented_methods-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/verify_constant_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireDoublable/with_doubled_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireObjectDouble/cdesc-FireObjectDouble.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/FireObjectDouble/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/RecursiveConstMethods/cdesc-RecursiveConstMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/RecursiveConstMethods/const_defined_on%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/RecursiveConstMethods/get_const_defined_on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/RecursiveConstMethods/recursive_const_defined%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/RecursiveConstMethods/recursive_const_get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/ShouldProxy/cdesc-ShouldProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/ShouldProxy/ensure_arity-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/ShouldProxy/expect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/ShouldProxy/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/ShouldProxy/support_arity-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/ShouldProxy/with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/arity-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/arity_description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/cdesc-SupportArityMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/failure_message_for_should-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/max_arity-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/min_arity-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/SupportArityMatcher/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/cdesc-Fire.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/class_double-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/configuration-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/configure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/find_original_value_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/fire_class_double-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/fire_double-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/fire_replaced_class_double-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Fire/instance_double-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Mocks/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/Mocks/cdesc-Mocks.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspec-fire-1.3.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/HISTORY
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/lib/rspec/fire.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/lib/rspec/fire/configuration.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/lib/rspec/fire/legacy.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/rspec-fire.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/spec/fire_double_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspec-fire-1.3.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rspec-fire-1.3.0.gemspec
