#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspec-fire
Version  : 1.3.0
Release  : 5
URL      : https://rubygems.org/downloads/rspec-fire-1.3.0.gem
Source0  : https://rubygems.org/downloads/rspec-fire-1.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core

%description
rspec-fire
==========
Checks that stubbed methods on your test double exist, but still allow you to run in isolation
when you choose. A failure will be triggered if an invalid method is being stubbed.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspec-fire-1.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-rspec-fire.gemspec

%build
gem build rubygem-rspec-fire.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspec-fire-1.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rspec-fire-1.3.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/HISTORY
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/lib/rspec/fire.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/lib/rspec/fire/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/lib/rspec/fire/legacy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/rspec-fire.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/spec/fire_double_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-fire-1.3.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rspec-fire-1.3.0.gemspec
